export enum SOCKET_EVENTS {
    FETCH_NOTES='FETCH_NOTES',
    CREATE='CREATE',
    UPDATE_VALUE='UPDATE_VALUE',
    MOVE='MOVE',
    CARD_CREATED= 'CARD_CREATED',
    NOTES_FETCHED='NOTES_FETCHED',
    DELETE='DELETE'
}

export enum REDUCER_EVENTS {
    ADD_NOTE='ADD_NOTE',
    SET_NOTES='SET_NOTES',
    CHANGE_VALUE='CHANGE_VALUE',
    MOVE='MOVE',
    REMOVE='REMOVE'
}